enum GameObjects {
    PLAYER,
    PLAYEROTHER,
    NPCAI,
    BULLETGUN,
    BULLETREVOLVER,
    BULLETSHOTGUN,
    LIFECONTAINER,
    REVOLVER,
    GUN,
    SHOTGUN,
    DYNAMITE,
    TREE,
    MEADOW,
    WATER,
    ROCK,
    ROAD,
    FORD
}

enum Infoboxes { PLAYER_FIXED, PLAYER_FLOATING, NPC_FLOATING }
